DROP TABLE IF EXISTS MATERIAL_LOANS CASCADE;
DROP TABLE IF EXISTS ROOM_PARTECIPANT CASCADE;
DROP TABLE IF EXISTS READING_ROOM CASCADE;
DROP TABLE IF EXISTS MATERIAL CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;


CREATE TABLE USERS (
    USERID SERIAL PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(30) NOT NULL UNIQUE,
    role VARCHAR(10) NOT NULL CHECK (role IN ('admin', 'user'))
);

CREATE TABLE MATERIAL (
    MATERIALID INT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL CHECK (TYPE IN (
        'book', 'journal', 'magazine', 'newspaper', 'researchpaper',
        'Magazine', 'Thesis', 'ConferencePaper', 'Referencematerial',
        'database', 'Archive', 'dataset', 'audioBook'
    )),
    TITLE VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(50) NOT NULL,
    SUMMARY TEXT NOT NULL,
    DATE_PUBLISHED DATE NOT NULL,
    PUBLISHER VARCHAR(50) NOT NULL,
    CONTRIBUTORS VARCHAR(100),
    FORMAT VARCHAR(20) NOT NULL CHECK (FORMAT IN ('print', 'digital', 'audiobook')),
    LANGUAGE VARCHAR(20) NOT NULL,
    IDENTIFIER VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MATERIAL_FILES (
    ID SERIAL PRIMARY KEY,  -- Fixed: Added SERIAL
    MATERIAL_ID BIGINT NOT NULL,  -- Fixed: Proper data type
    NAME VARCHAR(255) NOT NULL,  -- Fixed: Increased length for filenames
    FILE_SIZE BIGINT,  -- Fixed: BIGINT for large files
    FILE_TYPE VARCHAR(255),  -- Fixed: Increased length for MIME types
    FILE_CONTENT BYTEA,  -- Fixed: PostgreSQL BYTEA for binary data
    DOWNLOAD_COUNT INT DEFAULT 0,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Foreign key constraint
    FOREIGN KEY (MATERIAL_ID) REFERENCES MATERIAL(MATERIALID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MATERIAL_LOANS (
    LOANID SERIAL PRIMARY KEY,
    USERID BIGINT NOT NULL,  -- Changed to BIGINT to match USERS.USERID
    MATERIALID BIGINT NOT NULL,  -- Changed to BIGINT to match MATERIAL.MATERIALID
    BORROW_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    DUE_DATE DATE NOT NULL,
    RETURN_DATE DATE NULL,  -- NULL means not returned yet
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'RETURNED', 'OVERDUE', 'LOST')),
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Foreign key constraints
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MATERIALID) REFERENCES MATERIAL(MATERIALID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MATERIALTAGS (
    MATERIALTAGID SERIAL PRIMARY KEY,
    MATERIALID BIGINT NOT NULL,
    TYPE VARCHAR(50) NOT NULL CHECK (TYPE IN ('book', 'journal', 'magazine', 'newspaper', 'researchpaper',
        'Magazine', 'Thesis', 'ConferencePaper', 'Referencematerial',
        'database', 'Archive', 'dataset', 'audioBook')),
    TAGS JSONB DEFAULT '[]'::jsonb,
    FOREIGN KEY(MATERIALID) REFERENCES MATERIAL(MATERIALID) ON DELETE CASCADE ON UPDATE CASCADE
);